#!/usr/bin/python

movie_properties = [
					'title',
					'originaltitle',
					'votes',
					'playcount',
					'year',
					'genre',
					'studio',
					'country',
					'tagline',
					'plot',
					'runtime',
					'file',
					'plotoutline',
					'lastplayed',
					'trailer',
					'rating',
					'resume',
					'art',
					'streamdetails',
					'mpaa',
					'director',
					'writer',
					'cast',
					'dateadded',
					'imdbnumber']

episode_properties = [
					'title',
					'playcount',
					'season',
					'episode',
					'showtitle',
					'plot',
					'file',
					'rating',
					'resume',
					'tvshowid',
					'firstaired',
					'art',
					'streamdetails',
					'runtime',
					'director',
					'writer',
					'cast',
					'dateadded',
					'lastplayed']

season_properties = [
					'season',
					'episode',
					'art',
					'watchedepisodes',
					'showtitle',
					'playcount',
					'tvshowid']

tvshow_properties = [
					'title',
					'studio',
					'year',
					'plot',
					'cast',
					'rating',
					'votes',
					'genre',
					'episode',
					'season',
					'mpaa',
					'premiered',
					'playcount',
					'art',
					'dateadded',
					'watchedepisodes',
					'imdbnumber']