#!/usr/bin/python

movie_properties = [
                    'title',
                    'originaltitle',
                    'sorttitle',
                    'votes',
                    'playcount',
                    'year',
                    'genre',
                    'studio',
                    'country',
                    'tagline',
                    'plot',
                    'runtime',
                    'file',
                    'plotoutline',
                    'lastplayed',
                    'trailer',
                    'rating',
                    'userrating',
                    'resume',
                    'art',
                    'streamdetails',
                    'mpaa',
                    'director',
                    'writer',
                    'cast',
                    'dateadded',
                    'imdbnumber']

episode_properties = [
                    'title',
                    'playcount',
                    'season',
                    'episode',
                    'showtitle',
                    'originaltitle',
                    'plot',
                    'votes',
                    'file',
                    'rating',
                    'userrating',
                    'resume',
                    'tvshowid',
                    'firstaired',
                    'art',
                    'streamdetails',
                    'runtime',
                    'director',
                    'writer',
                    'cast',
                    'dateadded',
                    'lastplayed']

season_properties = [
                    'season',
                    'episode',
                    'art',
                    'userrating',
                    'watchedepisodes',
                    'showtitle',
                    'playcount',
                    'tvshowid']

tvshow_properties = [
                    'title',
                    'studio',
                    'year',
                    'plot',
                    'cast',
                    'rating',
                    'userrating',
                    'votes',
                    'genre',
                    'episode',
                    'season',
                    'runtime',
                    'mpaa',
                    'premiered',
                    'playcount',
                    'lastplayed',
                    'sorttitle',
                    'originaltitle',
                    'art',
                    'dateadded',
                    'watchedepisodes',
                    'imdbnumber']