# coding=utf-8

GENRES_TV = {
    "Action": ["Action", "Action & Adventure"],
    "Adventure": ["Adventure"],
    "Animation": ["Animation"],
    "Anime": ["Anime"],
    "Awards Show": ["Awards Show"],
    "Children": ["Children"],
    "Comedy": ["Comedy"],
    "Crime": ["Crime"],
    "Documentary": ["Documentary"],
    "Drama": ["Drama"],
    "Family": ["Family"],
    "Fantasy": ["Fantasy"],
    "Food": ["Food"],
    "Game Show": ["Game Show"],
    "History": ["History"],
    "Home and Garden": ["Home and Garden"],
    "Horror": ["Horror"],
    "Indie": ["Indie"],
    "Martial Arts": ["Martial Arts"],
    "Mini-Series": ["Mini-Series"],
    "Musical": ["Musical"],
    "Mystery": ["Mystery"],
    "News": ["News"],
    "Podcast": ["Podcast"],
    "Reality": ["Reality"],
    "Romance": ["Romance"],
    "Science Fiction": ["Science Fiction", "Science-Fiction", "Sci-Fi", "Sci-Fi & Fantasy"],
    "Soap": ["Soap"],
    "Sport": ["Sport"],
    "Suspense": ["Suspense"],
    "Talk Show": ["Talk Show"],
    "Thriller": ["Thriller"],
    "Travel": ["Travel"],
    "War": ["War", "War & Politics"],
    "Western": ["Western"],
}

GENRES_TV_BY_SYN = {v: k for k, values in GENRES_TV.items() for v in values}
