language: python
matrix:
  include:
    - python: "3.7.0"

# command to install dependencies
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.7.0" ]]; then
    pip install git+https://github.com/xbmc/addon-check.git;
    fi

# command to run tests
script:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.7.0" ]]; then
    kodi-addon-checker $TRAVIS_BUILD_DIR --branch=matrix;
    fi
