coverage:
  range: 50..100
  round: nearest
  status:
    project:
      default:
        target: 75%
        threshold: 6%
#        base: auto
#        branches: null
    patch: false
comment: false
ignore:
- test/
