# -*- encoding: utf-8 -*-
"""
    string constants

    Copyright (C) 2012-2016 python-twitch (https://github.com/ingwinlu/python-twitch)
    Copyright (C) 2016-2019 script.module.python.twitch

    This file is part of script.module.python.twitch

    SPDX-License-Identifier: GPL-3.0-only
    See LICENSES/GPL-3.0-only for more information.
"""

AFTER = 'after'
ALLOW_AUDIO_ONLY = 'allow_audio_only'
ALLOW_SOURCE = 'allow_source'
ALLOW_SPECTRE = 'allow_spectre'
AVATAR_IMAGE = 'avatar_image'
BAKING_BREAD = 'baking_bread'
BAKING_BROWNIES = 'baking_brownies'
BAKING_BROWNIES_TIMEOUT = 'baking_brownies_timeout'
BEFORE = 'before'
BROADCAST_TYPE = 'broadcast_type'
BROADCASTER_ID = 'broadcaster_id'
BROADCASTER_LANGUAGE = 'broadcaster_language'
BROADCASTS = 'broadcasts'
CDM = 'cdm'
CHANNEL = 'channel'
CHANNEL_FEED_ENABLED = 'channel_feed_enabled'
CHANNEL_ID = 'channel_id'
CLIP = 'clip'
CODE = 'code'
COLLECTION_ID = 'collection_id'
COMMENT_ID = 'comment_id'
COMMENTS = 'comments'
COMMUNITIES = 'communities'
COMMUNITY_ID = 'community_id'
COMMUNITY_IDS = 'community_ids'
CONTAINING_ITEM = 'containing_item'
CONTENT = 'content'
CONTROL = 'control'
COUNT = 'count'
COVER_IMAGE = 'cover_image'
CURSOR = 'cursor'
CLIENT_ID = 'client_id'
DATA = 'data'
DELAY = 'delay'
DESCRIPTION = 'description'
DIRECTION = 'direction'
DURATION = 'duration'
EMAIL = 'email'
EMOTE_ID = 'emote_id'
EMOTESETS = 'emotesets'
ENDED_AT = 'ended_at'
ERROR = 'error'
EXTENSION_ID = 'extension_id'
FAST_BREAD = 'fast_bread'
FEATURED = 'featured'
FIRST = 'first'
FOLLOWS = 'follows'
FROM_ID = 'from_id'
GAME = 'game'
GAME_ID = 'game_id'
HAS_DELAY = 'has_delay'
HLS = 'hls'
ID = 'id'
IDENTIFIER = 'identifier'
INCLUDE_ALL_ITEMS = 'include_all_items'
ITEM_ID = 'item_id'
LANGUAGE = 'language'
LIMIT = 'limit'
LIVE = 'live'
LIVE_ONLY = 'live_only'
LOGIN = 'login'
MANIFEST_ID = 'manifest_id'
MEDIAPLAYER = 'mediaplayer'
MESSAGE = 'message'
NAME = 'name'
NAUTH = 'nauth'
NAUTHSIG = 'nauthsig'
NEED_HTTPS = 'need_https'
NOTIFICATIONS = 'notifications'
OFFSET = 'offset'
PART = 'part'
PERIOD = 'period'
PLATFORM = 'platform'
PLAYER_BACKEND = 'player_backend'
PLAYLIST_INCLUDE_FRAMERATE = 'playlist_include_framerate'
POSITION = 'position'
POST_ID = 'post_id'
QUERY = 'query'
REASON = 'reason'
REASSIGNMENT_SUPPORTED = 'reassignment_supported'
RTQOS = 'rtqos'
RULES = 'rules'
SCE_PLATFORM = 'sce_platform'
SHARE = 'share'
SIG = 'sig'
SIGNATURE = 'signature'
SLUG = 'slug'
SORT = 'sort'
SORT_BY = 'sortby'
STARTED_AT = 'started_at'
STATUS = 'status'
STREAM_PLAYBACK_ACCESS_TOKEN = 'streamPlaybackAccessToken'
STREAM_TYPE = 'stream_type'
SUMMARY = 'summary'
TAG_ID = 'tag_id'
TAG_IDS = 'tag_ids'
TAG_LIST = 'tag_list'
TARGET_ID = 'target_id'
TEAM = 'team'
TITLE = 'title'
TO_ID = 'to_id'
TOKEN = 'token'
TRENDING = 'trending'
TYPE = 'type'
USER = 'user'
USERNAME = 'username'
USER_AGENT = 'User-Agent'
USER_AGENT_STRING = ('Mozilla/5.0 (Windows NT 6.1; WOW64; rv:6.0) '
                     'Gecko/20100101 Firefox/6.0')
USER_ID = 'user_id'
USER_LOGIN = 'user_login'
UPLOAD_TOKEN = 'upload_token'
VALUE = 'value'
VIDEO_ID = 'video_id'
VIDEO_PLAYBACK_ACCESS_TOKEN = 'videoPlaybackAccessToken'
VOD = 'vod'
WEB = 'web'
WV = 'wv'
XBOX_HEARTBEAT = 'xbox_heartbeat'
